package Interface;
import concert.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
public class MainMenu extends javax.swing.JFrame {
    
    public MainMenu() throws IOException {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        theBeatles = new javax.swing.JButton();
        Smash = new javax.swing.JButton();
        coboyJunior = new javax.swing.JButton();
        theBangles = new javax.swing.JButton();
        BlackPink = new javax.swing.JButton();
        CherryBelle = new javax.swing.JButton();
        logOUT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        theBeatles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Card tHEBEAT.png"))); // NOI18N
        theBeatles.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        theBeatles.setPreferredSize(new java.awt.Dimension(75, 100));
        theBeatles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theBeatlesActionPerformed(evt);
            }
        });
        getContentPane().add(theBeatles, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 25, -1, -1));

        Smash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Card sMASH.png"))); // NOI18N
        Smash.setPreferredSize(new java.awt.Dimension(75, 100));
        Smash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmashActionPerformed(evt);
            }
        });
        getContentPane().add(Smash, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 25, -1, -1));

        coboyJunior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Card cjr.png"))); // NOI18N
        coboyJunior.setPreferredSize(new java.awt.Dimension(75, 100));
        coboyJunior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coboyJuniorActionPerformed(evt);
            }
        });
        getContentPane().add(coboyJunior, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 25, -1, -1));

        theBangles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Card bang.png"))); // NOI18N
        theBangles.setPreferredSize(new java.awt.Dimension(75, 100));
        theBangles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theBanglesActionPerformed(evt);
            }
        });
        getContentPane().add(theBangles, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 145, -1, -1));

        BlackPink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cardbp.png"))); // NOI18N
        BlackPink.setPreferredSize(new java.awt.Dimension(75, 100));
        BlackPink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackPinkActionPerformed(evt);
            }
        });
        getContentPane().add(BlackPink, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 145, -1, -1));

        CherryBelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cardchib.png"))); // NOI18N
        CherryBelle.setPreferredSize(new java.awt.Dimension(75, 100));
        CherryBelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CherryBelleActionPerformed(evt);
            }
        });
        getContentPane().add(CherryBelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 145, -1, -1));

        logOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        logOUT.setBorder(null);
        logOUT.setBorderPainted(false);
        logOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOUTActionPerformed(evt);
            }
        });
        getContentPane().add(logOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 264, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BgLg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOUTActionPerformed
        LogIn back = new LogIn();
    }//GEN-LAST:event_logOUTActionPerformed

    private void theBeatlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theBeatlesActionPerformed
        TheBeatles.TestTheBeatles();
    }//GEN-LAST:event_theBeatlesActionPerformed

    private void theBanglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theBanglesActionPerformed
        TheBangles.TestTheB();
    }//GEN-LAST:event_theBanglesActionPerformed

    private void BlackPinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackPinkActionPerformed
        Blackpink.TestBp();
    }//GEN-LAST:event_BlackPinkActionPerformed

    private void CherryBelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CherryBelleActionPerformed
        Cherrybelle.TestCb();
    }//GEN-LAST:event_CherryBelleActionPerformed

    private void coboyJuniorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coboyJuniorActionPerformed
        Coboyjunior.TestCJR();
    }//GEN-LAST:event_coboyJuniorActionPerformed

    private void SmashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmashActionPerformed
        SMash.TestSmash();
    }//GEN-LAST:event_SmashActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainMenu().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BlackPink;
    private javax.swing.JButton CherryBelle;
    private javax.swing.JButton Smash;
    private javax.swing.JButton coboyJunior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOUT;
    private javax.swing.JButton theBangles;
    private javax.swing.JButton theBeatles;
    // End of variables declaration//GEN-END:variables
}
